### ISSUE TITLE
RGB LED usage and LED intensity

### ISSUE THREAD

**Issue by buckneri** [MajicDesigns/MultiBlink#1]
More of a question than an issue.

Is there a way to adjust the code to work with RGB LED'S? Mainly the intensity levels of each pwm pin would need to be able to be adjusted, which would then allow different light levels via SW vs resistors, and combining pins would allow RGB LED usage.

**Comment by MajicDesigns** [comment]
Sure, you just need to make the adjustments to defining the pins and the logic of how it works.
It is easier to make the adjustment to work with neopixel LEDs (like WS2812) as the color is easier to set directly and there are no PWM timing issues. I did this for a paid commission (so can't share the code) and it worked well.

**Comment by buckneri** [comment]
Good to know. I have some neopixels coming someday, so maybe another paid commission is on the horizon.

Additionally...

I noticed that the wreck buoy example gets out of sync, or rather the two led's get IN sync after a while instead of alternating.  Any idea what is causing this?

**Comment by MajicDesigns** [comment]
Which Multibink version are you referring to?

**Comment by buckneri** [comment]
V4.
In tinkercad, i don't think it syncs up, but on the actual Uno they end up getting in sync after a while, then separating again after a long time.

**Comment by MajicDesigns** [comment]
I tested on an Uno and never for a looong time, just enough to make sure the timing works. If a sequence is made up of 2 or more independent LEDS (ie, one flash on, one flash off), then they could get out of sync just from the processing time between the LEDs (ie, the millis() base value drifts by the processing time). The way to fix this is to keep the baseline millis() the same for every pass throught the LEDs. I think an easy solution here is to change the line
pT->nextWakeup = millis() + pT->state[cs].activeTime;
to 
pT->nextWakeup +=  pT->state[cs].activeTime;
